version: '3.7'
services:
    redis:
      image: redis:latest
      container_name: redis
      restart: always
      ports:
        - 6379:6379
    api:
      image: node:latest
      container_name: api
      restart: always
      depends_on:
         - redis
      ports:
        - 3000:3000
      environment:
        - REDIS_URL=redis
        - REDIS_PORT=6379
      volumes:
        - .:/usr/src/app
      working_dir: /usr/src/app
      command: npm run start